In [27]:
import pandas as pd

In [28]:
#load train dataset
train = pd.read_csv('train.csv',index_col='id')

print(train.shape)
train.head()

(61878, 94)

,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,...,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93,target
id,,,,,,,,,,,,,,,,,,,,,
1,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,Class_1
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Class_1
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Class_1
4,1,0,0,1,6,1,5,0,0,1,...,0,1,2,0,0,0,0,0,0,Class_1
5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,Class_1

In [29]:
#load test dataset
test = pd.read_csv('test.csv', index_col='id')

print(test.shape)
test.head()

(144368, 93)

,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,...,feat_84,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93
id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,3,...,0,0,11,1,20,0,0,0,0,0
2,2,2,14,16,0,0,0,0,0,0,...,0,0,0,0,0,4,0,0,2,0
3,0,1,12,1,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,1
4,0,0,0,1,0,0,0,0,0,0,...,0,3,1,0,0,0,0,0,0,0
5,1,0,0,1,0,0,1,2,0,3,...,0,0,0,0,0,0,0,9,0,0

In [30]:
#train data: seperate target column
label_name = "target"
feature_names = train.columns.difference([label_name])

feature_names

Index(['feat_1', 'feat_10', 'feat_11', 'feat_12', 'feat_13', 'feat_14',
       'feat_15', 'feat_16', 'feat_17', 'feat_18', 'feat_19', 'feat_2',
       'feat_20', 'feat_21', 'feat_22', 'feat_23', 'feat_24', 'feat_25',
       'feat_26', 'feat_27', 'feat_28', 'feat_29', 'feat_3', 'feat_30',
       'feat_31', 'feat_32', 'feat_33', 'feat_34', 'feat_35', 'feat_36',
       'feat_37', 'feat_38', 'feat_39', 'feat_4', 'feat_40', 'feat_41',
       'feat_42', 'feat_43', 'feat_44', 'feat_45', 'feat_46', 'feat_47',
       'feat_48', 'feat_49', 'feat_5', 'feat_50', 'feat_51', 'feat_52',
       'feat_53', 'feat_54', 'feat_55', 'feat_56', 'feat_57', 'feat_58',
       'feat_59', 'feat_6', 'feat_60', 'feat_61', 'feat_62', 'feat_63',
       'feat_64', 'feat_65', 'feat_66', 'feat_67', 'feat_68', 'feat_69',
       'feat_7', 'feat_70', 'feat_71', 'feat_72', 'feat_73', 'feat_74',
       'feat_75', 'feat_76', 'feat_77', 'feat_78', 'feat_79', 'feat_8',
       'feat_80', 'feat_81', 'feat_82', 'feat_83', 'feat_84', 'feat_85',
       'feat_86', 'feat_87', 'feat_88', 'feat_89', 'feat_9', 'feat_90',
       'feat_91', 'feat_92', 'feat_93'],
      dtype='object')

In [31]:
X_train = train[feature_names]

print(X_train.shape)
X_train.head()

(61878, 93)

,feat_1,feat_10,feat_11,feat_12,feat_13,feat_14,feat_15,feat_16,feat_17,feat_18,...,feat_85,feat_86,feat_87,feat_88,feat_89,feat_9,feat_90,feat_91,feat_92,feat_93
id,,,,,,,,,,,,,,,,,,,,,
1,1,0,1,0,0,0,0,0,2,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,1,0,0,1,1,0,...,0,1,2,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,4,0,...,1,0,0,0,0,0,1,0,0,0

In [32]:
X_test = test[feature_names]

print(X_test.shape)
X_test.head()

(144368, 93)

,feat_1,feat_10,feat_11,feat_12,feat_13,feat_14,feat_15,feat_16,feat_17,feat_18,...,feat_85,feat_86,feat_87,feat_88,feat_89,feat_9,feat_90,feat_91,feat_92,feat_93
id,,,,,,,,,,,,,,,,,,,,,
1,0,3,0,0,0,3,2,1,0,0,...,0,11,1,20,0,0,0,0,0,0
2,2,0,0,0,0,0,2,2,0,0,...,0,0,0,0,4,0,0,0,2,0
3,0,0,7,1,0,0,0,7,0,2,...,0,0,0,2,0,0,0,0,0,1
4,0,0,0,0,0,0,21,3,0,0,...,3,1,0,0,0,0,0,0,0,0
5,1,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,9,0,0

In [33]:
y_train = train[label_name]

print(y_train.shape)
y_train.head()

(61878,)

id
1    Class_1
2    Class_1
3    Class_1
4    Class_1
5    Class_1
Name: target, dtype: object

In [16]:
from lightgbm import LGBMClassifier

model = LGBMClassifier()
%time model.fit(X_train, y_train)

Wall time: 29.2 s

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='split', learning_rate=0.1, max_depth=-1,
        min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
        n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
        random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
        subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

#### Searching for the Best Hyperparameter

In [34]:
import numpy as np
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score

random_state = 42
num_loop = 100
kf = StratifiedKFold(n_splits=5, random_state=random_state, shuffle=False) #5-cv
finer_hyperparameters_list = []

for loop in range(num_loop):
    n_estimators = np.random.randint(500, 3000)
    num_leaves =  np.random.randint(100, 200)
    min_child_samples = np.random.randint(50, 100)
    min_child_weight = np.random.uniform(0.5, 0.8) 
    subsample = np.random.uniform(0.4, 0.8) 
    colsample_bytree = np.random.uniform(0.4, 0.7)
    reg_alpha = 10 ** -np.random.uniform(low=3, high=8)
    reg_lambda = 10 ** -np.random.uniform(low=5, high=15)
    learning_rate = 10 ** -np.random.uniform(low=0.9, high=3)

    parameters ={'loop': loop,
                 'n_estimators': n_estimators,
                 'num_leaves': num_leaves, 
                 'min_child_samples': min_child_samples, 
                 'min_child_weight': min_child_weight,
                 'subsample': subsample, 
                 'colsample_bytree': colsample_bytree,
                 'reg_alpha': reg_alpha,
                 'reg_lambda': reg_lambda,
                 'n_estimators': n_estimators,
                 'learning_rate' : learning_rate,
                 'random_state': random_state}

    fit_params = {'verbose':0}
    
    model = LGBMClassifier(**parameters)
    
    score = cross_val_score(model, X_train, y_train, cv=kf, fit_params=fit_params, scoring='neg_log_loss').mean()
    score = -1.0 * score
    
    parameters['score'] = score
    
    print(f"{loop:2} best iteration = {parameters['n_estimators']}, Score = {parameters['score']:.6f}")
    
    finer_hyperparameters_list.append(parameters)
    finer_hyperparameters_data = pd.DataFrame(finer_hyperparameters_list)
    finer_hyperparameters_data = finer_hyperparameters_data.sort_values(by="score")
    
    finer_hyperparameters_data.to_csv("paramsearch.csv")
    
finer_hyperparameters_data.head(10)

KeyboardInterrupt:

In [12]:
from lightgbm import LGBMClassifier

model = LGBMClassifier(learning_rate=6.991383e-03,
                       n_estimators=2486,
                       num_leaves=218,
                       max_bin=356,
                       min_child_samples=115,
                       min_child_weight=2.668823,
                       subsample=0.630275,
                       colsample_bytree=0.480936,
                       reg_alpha=1.058085e-06,
                       reg_lambda=6.960670e-09,
                       random_state=42)
model

LGBMClassifier(boosting_type='gbdt', class_weight=None,
        colsample_bytree=0.480936, learning_rate=0.006991383, max_bin=356,
        max_depth=-1, min_child_samples=115, min_child_weight=2.668823,
        min_split_gain=0.0, n_estimators=2486, n_jobs=-1, num_leaves=218,
        objective=None, random_state=42, reg_alpha=1.058085e-06,
        reg_lambda=6.96067e-09, silent=True, subsample=0.630275,
        subsample_for_bin=200000, subsample_freq=0)

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

kf = StratifiedKFold(n_splits=5, random_state=random_state, shuffle=False)

fit_params = {'verbose': 0}

score = cross_val_score(model, X_train, y_train, cv=kf,
                        fit_params=fit_params, scoring='neg_log_loss').mean()
score = -1.0 * score

print(f"Score = {score:.5f}")

In [13]:
model.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None,
        colsample_bytree=0.480936, learning_rate=0.006991383, max_bin=356,
        max_depth=-1, min_child_samples=115, min_child_weight=2.668823,
        min_split_gain=0.0, n_estimators=2486, n_jobs=-1, num_leaves=218,
        objective=None, random_state=42, reg_alpha=1.058085e-06,
        reg_lambda=6.96067e-09, silent=True, subsample=0.630275,
        subsample_for_bin=200000, subsample_freq=0)

In [14]:
predictions = model.predict_proba(X_test)

print(predictions.shape)
predictions

(144368, 9)

array([[  2.24644254e-04,   9.75604148e-02,   1.30055601e-01, ...,
          2.64305291e-03,   2.57551850e-04,   5.71026120e-05],
       [  2.71608033e-03,   4.31660559e-03,   1.36982284e-03, ...,
          9.61980522e-04,   6.70048109e-01,   7.40723241e-04],
       [  4.83850053e-06,   1.93566029e-05,   1.01470945e-05, ...,
          7.11435731e-06,   2.04477593e-04,   6.33753804e-06],
       ...,
       [  3.12497467e-04,   6.37192885e-01,   2.96945568e-01, ...,
          1.96801725e-03,   2.54512526e-04,   9.07160860e-05],
       [  2.42389136e-04,   3.53553356e-01,   2.33072622e-02, ...,
          7.09474773e-04,   6.02472901e-05,   6.43027879e-05],
       [  1.62822189e-04,   6.07391326e-01,   3.49726203e-01, ...,
          1.86872494e-02,   1.15392596e-04,   7.49704953e-05]])

In [15]:
#file for submission
submission_sample = pd.read_csv("data/sampleSubmission.csv", index_col="id")

print(submission_sample.shape)
submission_sample.head()

(144368, 9)

,Class_1,Class_2,Class_3,Class_4,Class_5,Class_6,Class_7,Class_8,Class_9
id,,,,,,,,,
1,1,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0

In [16]:
submission = pd.DataFrame(predictions, index=submission_sample.index, columns=model.classes_)

print(submission.shape)
submission.head()

(144368, 9)

,Class_1,Class_2,Class_3,Class_4,Class_5,Class_6,Class_7,Class_8,Class_9
id,,,,,,,,,
1,0.000225,0.097560,0.130056,0.768985,0.000056,0.000160,0.002643,0.000258,0.000057
2,0.002716,0.004317,0.001370,0.000374,0.000519,0.318954,0.000962,0.670048,0.000741
3,0.000005,0.000019,0.000010,0.000007,0.000002,0.999739,0.000007,0.000204,0.000006
4,0.000150,0.636784,0.359679,0.002419,0.000055,0.000074,0.000173,0.000131,0.000536
5,0.163521,0.000997,0.001311,0.000385,0.000495,0.002239,0.002515,0.048232,0.780306

In [18]:
submission.to_csv("otto-submission.csv")